### ISSUE TITLE
Samme decimalseparator på begge sider

### ISSUE THREAD

**Issue by larsnaesbye** [SDFIdk/Koordinattransformation#53]
På inputsiden benyttes komma som decimalseparator, på output-siden punktum. Det bør nok være komma ift. dansk brug men i hvert fald det samme begge steder.

![image](https://user-images.githubusercontent.com/7767079/203294871-8f3db692-4255-4bbb-99ec-82078728e95c.png)

**Comment by PelleSwelle** [comment]
jeg laver det med punktummer for at imødekomme internationale standarder.

**Comment by larsnaesbye** [comment]
Den er vel lukket nu?
