### ISSUE TITLE
Formatteringsfejl ved tryk på grad-format-knapperne 

### ISSUE THREAD

**Issue by larsnaesbye** [SDFIdk/Koordinattransformation#58]
Det ser ud til at formatet ændres uhensigtsmæssigt ved tryk på grad-format-knapperne.

![ny_web_transformation2](https://user-images.githubusercontent.com/7767079/206680209-90f53805-e3db-4206-a837-1670db6bc442.jpg)

**Comment by PelleSwelle** [comment]
Jeg er ret sikker på, at det er med vilje. At når EPSG'en er i grader, vises felterne under hinanden i stedet for ved siden af hinanden.
Hvis vi ikke kan lide det, laver vi det selvfølgelig bare om

**Comment by kbevers** [comment]
Så vidt jeg kan se opfører den sig som tiltænkt

**Comment by PelleSwelle** [comment]
Skal vi lade den hænge indtil Lars fortæller om en detalje, vi måske overser?

**Comment by kbevers** [comment]
Ja

**Comment by larsnaesbye** [comment]
Det var Keller der gjorde opmærksom på fejlen :-)

**Comment by kbevers** [comment]
Closed with #69
