### ISSUE TITLE
Tilføjelse af EPSG kode ved valg af referencesystem

### ISSUE THREAD

**Issue by casperjepsen** [SDFIdk/Koordinattransformation#59]
Det ville være brugbart og ville måske undgå fejl for brugeren, hvis det var hardkodet hvilket EPSG kode det var man brugte.  
![image](https://user-images.githubusercontent.com/60091374/206709815-dc180a2a-0458-469a-b2df-ff6f142466bf.png)

EPSG koden kunne stå i en parentes eller vises som en mouseover.

**Comment by kbevers** [comment]
Det er tilsyneladende blevet overset, da det fremgår af mockups:
![image](https://user-images.githubusercontent.com/13132571/207037893-8c6297e3-e141-4d5e-a51b-66451fb710fe.png)
